### ISSUE TITLE
Warning message: port 9230 is already used

### ISSUE THREAD

**Issue by stevez** [cenfun/nextjs-with-playwright-istanbul#1]
@cenfun, thanks for your example repo, I can run it in my local, thanks.
One more thing I got the following message:
```
[WebServer] Starting inspector on 127.0.0.1:9230 failed: address already in use
```
I wonder is this normal? Or I should use a different port, like 9229?
 
Thanks

**Comment by cenfun** [comment]
see https://github.com/cenfun/nextjs-with-playwright-istanbul?tab=readme-ov-file#debugging-port
